version: "3.8"
services:
  app:
    build: .
    command: ["npm", "run", "dev"]
    volumes:
      - .:/usr/local/app
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0 # disable ssl verification.
    ports:
      - 3000:3000
  proxy:
    image: nginx:latest
    ports:
      - 4441:4441
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./proxy/certs:/etc/ssl/certs:ro
    restart: always
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
